/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainGUI;

import java.awt.CardLayout;
import javax.swing.JFrame;

/**
 *
 * @author Colin
 */
public class MainContainerFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainContainerFrame
     */
    public MainContainerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JTabbedPane();
        calendarTab = new javax.swing.JPanel();
        floorLayoutTab = new javax.swing.JPanel();
        floorLayoutPanel = new javax.swing.JPanel();
        NewReservationButton = new javax.swing.JButton();
        GuestSearchButton = new javax.swing.JButton();
        FloorSelector = new javax.swing.JComboBox();
        MainPanel = new javax.swing.JPanel();
        Floor1Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RoomDataButton = new javax.swing.JButton();
        Floor2Panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Floor3Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        kitchenTab = new javax.swing.JPanel();
        kitchenPanel = new javax.swing.JPanel();
        RestaurantHostCurrentOrdersPanel = new javax.swing.JPanel();
        NewOrderButton = new javax.swing.JButton();
        OrderHistoryButton = new javax.swing.JButton();
        EditOrderButton = new javax.swing.JButton();
        RemoveOrderButton = new javax.swing.JButton();
        ViewMenuButton = new javax.swing.JButton();
        ViewInventoryButton = new javax.swing.JButton();
        EditInventoryButton = new javax.swing.JButton();
        CurrentOrdersLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        checkoutTab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CheckoutGuestSearchButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        ProcessPaymentButton = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CheckOutButton = new javax.swing.JButton();
        searchTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout calendarTabLayout = new javax.swing.GroupLayout(calendarTab);
        calendarTab.setLayout(calendarTabLayout);
        calendarTabLayout.setHorizontalGroup(
            calendarTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        calendarTabLayout.setVerticalGroup(
            calendarTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        mainFrame.addTab("Calendar", calendarTab);

        NewReservationButton.setText("New Reservation");
        NewReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewReservationButtonActionPerformed(evt);
            }
        });

        GuestSearchButton.setText("Guest Search");
        GuestSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestSearchButtonActionPerformed(evt);
            }
        });

        FloorSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Floor 1", "Floor 2", "Floor 3" }));
        FloorSelector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                FloorSelectorItemStateChanged(evt);
            }
        });

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Floor 1");

        RoomDataButton.setText("Room Data");
        RoomDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Floor1PanelLayout = new javax.swing.GroupLayout(Floor1Panel);
        Floor1Panel.setLayout(Floor1PanelLayout);
        Floor1PanelLayout.setHorizontalGroup(
            Floor1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Floor1PanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(RoomDataButton)
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        Floor1PanelLayout.setVerticalGroup(
            Floor1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Floor1PanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(Floor1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(RoomDataButton))
                .addContainerGap(312, Short.MAX_VALUE))
        );

        MainPanel.add(Floor1Panel, "card2");

        jLabel2.setText("Floor2");

        javax.swing.GroupLayout Floor2PanelLayout = new javax.swing.GroupLayout(Floor2Panel);
        Floor2Panel.setLayout(Floor2PanelLayout);
        Floor2PanelLayout.setHorizontalGroup(
            Floor2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Floor2PanelLayout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(245, 245, 245))
        );
        Floor2PanelLayout.setVerticalGroup(
            Floor2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Floor2PanelLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel2)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        MainPanel.add(Floor2Panel, "card3");

        jLabel3.setText("Floor3");

        javax.swing.GroupLayout Floor3PanelLayout = new javax.swing.GroupLayout(Floor3Panel);
        Floor3Panel.setLayout(Floor3PanelLayout);
        Floor3PanelLayout.setHorizontalGroup(
            Floor3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Floor3PanelLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel3)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        Floor3PanelLayout.setVerticalGroup(
            Floor3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Floor3PanelLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel3)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        MainPanel.add(Floor3Panel, "card4");

        javax.swing.GroupLayout floorLayoutPanelLayout = new javax.swing.GroupLayout(floorLayoutPanel);
        floorLayoutPanel.setLayout(floorLayoutPanelLayout);
        floorLayoutPanelLayout.setHorizontalGroup(
            floorLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floorLayoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(floorLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(floorLayoutPanelLayout.createSequentialGroup()
                        .addComponent(FloorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NewReservationButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GuestSearchButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        floorLayoutPanelLayout.setVerticalGroup(
            floorLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floorLayoutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(floorLayoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FloorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewReservationButton)
                    .addComponent(GuestSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout floorLayoutTabLayout = new javax.swing.GroupLayout(floorLayoutTab);
        floorLayoutTab.setLayout(floorLayoutTabLayout);
        floorLayoutTabLayout.setHorizontalGroup(
            floorLayoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(floorLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        floorLayoutTabLayout.setVerticalGroup(
            floorLayoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(floorLayoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainFrame.addTab("Floor Layout", floorLayoutTab);

        RestaurantHostCurrentOrdersPanel.setBackground(new java.awt.Color(255, 255, 255));
        RestaurantHostCurrentOrdersPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout RestaurantHostCurrentOrdersPanelLayout = new javax.swing.GroupLayout(RestaurantHostCurrentOrdersPanel);
        RestaurantHostCurrentOrdersPanel.setLayout(RestaurantHostCurrentOrdersPanelLayout);
        RestaurantHostCurrentOrdersPanelLayout.setHorizontalGroup(
            RestaurantHostCurrentOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );
        RestaurantHostCurrentOrdersPanelLayout.setVerticalGroup(
            RestaurantHostCurrentOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        NewOrderButton.setText("New Order");
        NewOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewOrderButtonActionPerformed(evt);
            }
        });

        OrderHistoryButton.setText("Order History");
        OrderHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderHistoryButtonActionPerformed(evt);
            }
        });

        EditOrderButton.setText("Edit Order");
        EditOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditOrderButtonActionPerformed(evt);
            }
        });

        RemoveOrderButton.setText("Remove Order");
        RemoveOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveOrderButtonActionPerformed(evt);
            }
        });

        ViewMenuButton.setText("View Menu");
        ViewMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMenuButtonActionPerformed(evt);
            }
        });

        ViewInventoryButton.setText("View Inventory");
        ViewInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewInventoryButtonActionPerformed(evt);
            }
        });

        EditInventoryButton.setText("Edit Inventory");
        EditInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditInventoryButtonActionPerformed(evt);
            }
        });

        CurrentOrdersLabel1.setFont(CurrentOrdersLabel1.getFont().deriveFont(CurrentOrdersLabel1.getFont().getSize()+6f));
        CurrentOrdersLabel1.setText("Current Orders");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setText("Active Orders");

        javax.swing.GroupLayout kitchenPanelLayout = new javax.swing.GroupLayout(kitchenPanel);
        kitchenPanel.setLayout(kitchenPanelLayout);
        kitchenPanelLayout.setHorizontalGroup(
            kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitchenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrderHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(EditOrderButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(RemoveOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(ViewMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(ViewInventoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(EditInventoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RestaurantHostCurrentOrdersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(kitchenPanelLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(CurrentOrdersLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(120, 120, 120))
        );
        kitchenPanelLayout.setVerticalGroup(
            kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitchenPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentOrdersLabel1)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kitchenPanelLayout.createSequentialGroup()
                        .addComponent(NewOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OrderHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EditOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RemoveOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ViewMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ViewInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EditInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RestaurantHostCurrentOrdersPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout kitchenTabLayout = new javax.swing.GroupLayout(kitchenTab);
        kitchenTab.setLayout(kitchenTabLayout);
        kitchenTabLayout.setHorizontalGroup(
            kitchenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
            .addGroup(kitchenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kitchenTabLayout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(kitchenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        kitchenTabLayout.setVerticalGroup(
            kitchenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
            .addGroup(kitchenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kitchenTabLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kitchenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainFrame.addTab("Kitchen", kitchenTab);

        jLabel4.setText("Guest ID:");

        jTextField1.setText("jTextField1");

        CheckoutGuestSearchButton.setText("Guest Search");
        CheckoutGuestSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutGuestSearchButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Payment Information");

        jLabel6.setText("CC #:");

        jLabel7.setText("Expiration");

        jLabel8.setText("CVV");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01 - Jan", "02 - Feb", "03 - Mar", "04 - Apr", "05 - May", "06 - Jun", "07 - Jul", "08 - Aug", "09 - Sep", "10 - Oct", "11 - Nov", "12 - Dec" }));

        jLabel9.setText("/");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        ProcessPaymentButton.setText("Process Payment");
        ProcessPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessPaymentButtonActionPerformed(evt);
            }
        });

        jTextField4.setText("jTextField4");

        jLabel10.setText("Result");

        CheckOutButton.setText("Check Out");
        CheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkoutTabLayout = new javax.swing.GroupLayout(checkoutTab);
        checkoutTab.setLayout(checkoutTabLayout);
        checkoutTabLayout.setHorizontalGroup(
            checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutTabLayout.createSequentialGroup()
                .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkoutTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkoutTabLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckoutGuestSearchButton))
                            .addComponent(jLabel5)
                            .addGroup(checkoutTabLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(checkoutTabLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(checkoutTabLayout.createSequentialGroup()
                                .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(checkoutTabLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(checkoutTabLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ProcessPaymentButton))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(checkoutTabLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(CheckOutButton)))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        checkoutTabLayout.setVerticalGroup(
            checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckoutGuestSearchButton))
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProcessPaymentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(53, 53, 53)
                .addComponent(CheckOutButton)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        mainFrame.addTab("Check Out", checkoutTab);

        javax.swing.GroupLayout searchTabLayout = new javax.swing.GroupLayout(searchTab);
        searchTab.setLayout(searchTabLayout);
        searchTabLayout.setHorizontalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        searchTabLayout.setVerticalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        mainFrame.addTab("Search/Update", searchTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(mainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckOutButtonActionPerformed
        // Do stuff here.
    }//GEN-LAST:event_CheckOutButtonActionPerformed

    private void ProcessPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessPaymentButtonActionPerformed
        // Do stuff here.
    }//GEN-LAST:event_ProcessPaymentButtonActionPerformed

    private void CheckoutGuestSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutGuestSearchButtonActionPerformed
        FrontDeskGUI.GuestSearchFrame GuestSearchFrame = new FrontDeskGUI.GuestSearchFrame(); //Create a new instance of the frame
        GuestSearchFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_CheckoutGuestSearchButtonActionPerformed

    private void EditInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditInventoryButtonActionPerformed
        RestaurantHostGUI.EditInventoryFrame EditInventoryFrame = new RestaurantHostGUI.EditInventoryFrame(); //Create a new instance of the frame
        EditInventoryFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_EditInventoryButtonActionPerformed

    private void ViewInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewInventoryButtonActionPerformed
        RestaurantHostGUI.ViewInventoryFrame ViewInventoryFrame = new RestaurantHostGUI.ViewInventoryFrame(); //Create a new instance of the frame
        ViewInventoryFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_ViewInventoryButtonActionPerformed

    private void ViewMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMenuButtonActionPerformed
        RestaurantHostGUI.ViewMenuFrame ViewMenuFrame = new RestaurantHostGUI.ViewMenuFrame(); //Create a new instance of the frame
        ViewMenuFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_ViewMenuButtonActionPerformed

    private void RemoveOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveOrderButtonActionPerformed
        // Do stuff here.
    }//GEN-LAST:event_RemoveOrderButtonActionPerformed

    private void EditOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditOrderButtonActionPerformed
        RestaurantHostGUI.OrderFrame OrderFrame = new RestaurantHostGUI.OrderFrame(); //Create a new instance of the frame
        OrderFrame.setVisible(true); //Make the frame visible
        // Not exactly sure how this is going to work.
    }//GEN-LAST:event_EditOrderButtonActionPerformed

    private void OrderHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderHistoryButtonActionPerformed
        RestaurantHostGUI.OrderHistoryFrame OrderHistoryFrame = new RestaurantHostGUI.OrderHistoryFrame(); //Create a new instance of the frame
        OrderHistoryFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_OrderHistoryButtonActionPerformed

    private void NewOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewOrderButtonActionPerformed
        RestaurantHostGUI.OrderFrame OrderFrame = new RestaurantHostGUI.OrderFrame(); //Create a new instance of the frame
        OrderFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_NewOrderButtonActionPerformed

    private void RoomDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomDataButtonActionPerformed
        FrontDeskGUI.RoomDataFrame Room1 = new FrontDeskGUI.RoomDataFrame(); // Create a new instance of the frame
        Room1.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_RoomDataButtonActionPerformed

    private void FloorSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FloorSelectorItemStateChanged
        /*
        @Pre
        Display the floor layout for the floor selected.
        */
    }//GEN-LAST:event_FloorSelectorItemStateChanged

    private void GuestSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestSearchButtonActionPerformed
        FrontDeskGUI.GuestSearchFrame GuestSearchFrame = new FrontDeskGUI.GuestSearchFrame(); //Create a new instance of the frame
        GuestSearchFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_GuestSearchButtonActionPerformed

    private void NewReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewReservationButtonActionPerformed
        FrontDeskGUI.NewReservationFrame NewReservationFrame = new FrontDeskGUI.NewReservationFrame(); //Create a new instance of the frame
        NewReservationFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_NewReservationButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainContainerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainContainerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainContainerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainContainerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainContainerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JButton CheckoutGuestSearchButton;
    private javax.swing.JLabel CurrentOrdersLabel1;
    private javax.swing.JButton EditInventoryButton;
    private javax.swing.JButton EditOrderButton;
    private javax.swing.JPanel Floor1Panel;
    private javax.swing.JPanel Floor2Panel;
    private javax.swing.JPanel Floor3Panel;
    private javax.swing.JComboBox FloorSelector;
    private javax.swing.JButton GuestSearchButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton NewOrderButton;
    private javax.swing.JButton NewReservationButton;
    private javax.swing.JButton OrderHistoryButton;
    private javax.swing.JButton ProcessPaymentButton;
    private javax.swing.JButton RemoveOrderButton;
    private javax.swing.JPanel RestaurantHostCurrentOrdersPanel;
    private javax.swing.JButton RoomDataButton;
    private javax.swing.JButton ViewInventoryButton;
    private javax.swing.JButton ViewMenuButton;
    private javax.swing.JPanel calendarTab;
    private javax.swing.JPanel checkoutTab;
    private javax.swing.JPanel floorLayoutPanel;
    private javax.swing.JPanel floorLayoutTab;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel kitchenPanel;
    private javax.swing.JPanel kitchenTab;
    private javax.swing.JTabbedPane mainFrame;
    private javax.swing.JPanel searchTab;
    // End of variables declaration//GEN-END:variables
}
