/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainframe.gui;

import static engine.InputManager.isInteger;
import engine.OrderDBManager;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Colin
 */
public class MainContainerFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainContainerFrame
     */
    public MainContainerFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainFrame = new javax.swing.JTabbedPane();
        reserveTab = new javax.swing.JPanel();
        newReservationButton = new javax.swing.JButton();
        GuestSearchButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        CurrentReservationTable = new javax.swing.JTable();
        floorLayoutTab = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kitchenTab = new javax.swing.JPanel();
        kitchenPanel = new javax.swing.JPanel();
        CurrentOrdersLabel1 = new javax.swing.JLabel();
        activeOrdersLabel = new javax.swing.JLabel();
        NewOrderButton = new javax.swing.JButton();
        OrderHistoryButton = new javax.swing.JButton();
        ViewMenuButton = new javax.swing.JButton();
        ViewInventoryButton = new javax.swing.JButton();
        EditInventoryButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        CurrentOrderTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        ActiveOrderOutput = new javax.swing.JTextArea();
        checkoutTab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        guestIDField = new javax.swing.JTextField();
        CheckoutGuestSearchButton = new javax.swing.JButton();
        paymentInfoLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ccNumberField = new javax.swing.JTextField();
        ccCVVField = new javax.swing.JTextField();
        ccMonthField = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        ccYearField = new javax.swing.JComboBox();
        ProcessPaymentButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        CheckOutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkoutInfoOutput = new javax.swing.JTextArea();
        GuestInfoLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        checkoutOutputField = new javax.swing.JTextArea();
        cashButton = new javax.swing.JButton();
        totalAmountDueLabel = new javax.swing.JLabel();
        totalAmountDueField = new javax.swing.JTextField();
        changeDueField = new javax.swing.JTextField();
        changeDueLabel = new javax.swing.JLabel();
        amountPaidLabel = new javax.swing.JLabel();
        amountPaidField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainFrame.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainFrameStateChanged(evt);
            }
        });

        newReservationButton.setText("New Reservation");
        newReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newReservationButtonActionPerformed(evt);
            }
        });

        GuestSearchButton.setText("Guest Search");
        GuestSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuestSearchButtonActionPerformed(evt);
            }
        });

        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        CurrentReservationTable.setAutoCreateRowSorter(true);
        CurrentReservationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Guest ID", "# Persons", "Guest Name", "Room Number", "Check Out Date", "Check In Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CurrentReservationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CurrentReservationTableMouseClicked(evt);
            }
        });
        CurrentReservationTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CurrentReservationTableFocusGained(evt);
            }
        });
        CurrentReservationTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CurrentReservationTableKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(CurrentReservationTable);

        javax.swing.GroupLayout reserveTabLayout = new javax.swing.GroupLayout(reserveTab);
        reserveTab.setLayout(reserveTabLayout);
        reserveTabLayout.setHorizontalGroup(
            reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTabLayout.createSequentialGroup()
                .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserveTabLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GuestSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE))
                    .addGroup(reserveTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LogOutButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        reserveTabLayout.setVerticalGroup(
            reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reserveTabLayout.createSequentialGroup()
                .addGroup(reserveTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reserveTabLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(newReservationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GuestSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(reserveTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(LogOutButton)
                .addContainerGap())
        );

        mainFrame.addTab("Reservation", reserveTab);

        floorLayoutTab.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainframe/resources/floorlayout.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout floorLayoutTabLayout = new javax.swing.GroupLayout(floorLayoutTab);
        floorLayoutTab.setLayout(floorLayoutTabLayout);
        floorLayoutTabLayout.setHorizontalGroup(
            floorLayoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(floorLayoutTabLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        floorLayoutTabLayout.setVerticalGroup(
            floorLayoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainFrame.addTab("Floor Layout", floorLayoutTab);

        CurrentOrdersLabel1.setFont(CurrentOrdersLabel1.getFont().deriveFont(CurrentOrdersLabel1.getFont().getSize()+6f));
        CurrentOrdersLabel1.setText("Current Orders");

        activeOrdersLabel.setFont(activeOrdersLabel.getFont().deriveFont(activeOrdersLabel.getFont().getSize()+6f));
        activeOrdersLabel.setText("Active Order");

        NewOrderButton.setText("New Order");
        NewOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewOrderButtonActionPerformed(evt);
            }
        });

        OrderHistoryButton.setText("Order History");
        OrderHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderHistoryButtonActionPerformed(evt);
            }
        });

        ViewMenuButton.setText("View Menu");
        ViewMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewMenuButtonActionPerformed(evt);
            }
        });

        ViewInventoryButton.setText("View Inventory");
        ViewInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewInventoryButtonActionPerformed(evt);
            }
        });

        EditInventoryButton.setText("Edit Inventory");
        EditInventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditInventoryButtonActionPerformed(evt);
            }
        });

        CurrentOrderTable.setAutoCreateRowSorter(true);
        CurrentOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Date", "Time", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CurrentOrderTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CurrentOrderTableFocusGained(evt);
            }
        });
        CurrentOrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CurrentOrderTableMouseClicked(evt);
            }
        });
        CurrentOrderTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CurrentOrderTableKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(CurrentOrderTable);

        ActiveOrderOutput.setColumns(20);
        ActiveOrderOutput.setRows(5);
        ActiveOrderOutput.setFocusable(false);
        jScrollPane6.setViewportView(ActiveOrderOutput);

        javax.swing.GroupLayout kitchenPanelLayout = new javax.swing.GroupLayout(kitchenPanel);
        kitchenPanel.setLayout(kitchenPanelLayout);
        kitchenPanelLayout.setHorizontalGroup(
            kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitchenPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitchenPanelLayout.createSequentialGroup()
                        .addComponent(CurrentOrdersLabel1)
                        .addGap(221, 221, 221)
                        .addComponent(activeOrdersLabel)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitchenPanelLayout.createSequentialGroup()
                        .addGroup(kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EditInventoryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OrderHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        kitchenPanelLayout.setVerticalGroup(
            kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kitchenPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CurrentOrdersLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(activeOrdersLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kitchenPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(kitchenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane6)))
                    .addGroup(kitchenPanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(NewOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OrderHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ViewMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ViewInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EditInventoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kitchenTabLayout = new javax.swing.GroupLayout(kitchenTab);
        kitchenTab.setLayout(kitchenTabLayout);
        kitchenTabLayout.setHorizontalGroup(
            kitchenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kitchenTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kitchenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        kitchenTabLayout.setVerticalGroup(
            kitchenTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kitchenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainFrame.addTab("Kitchen", kitchenTab);

        jLabel4.setText("Guest ID:");

        guestIDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                guestIDFieldFocusLost(evt);
            }
        });

        CheckoutGuestSearchButton.setText("Guest Search");
        CheckoutGuestSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutGuestSearchButtonActionPerformed(evt);
            }
        });

        paymentInfoLabel.setText("Payment Information");

        jLabel6.setText("CC #:");

        jLabel7.setText("Expiration");

        jLabel8.setText("CVV");

        ccMonthField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jLabel9.setText("/");

        ccYearField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));

        ProcessPaymentButton.setText("Process Credit Card");
        ProcessPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessPaymentButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Result");

        CheckOutButton.setText("Check Out");
        CheckOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckOutButtonActionPerformed(evt);
            }
        });

        checkoutInfoOutput.setEditable(false);
        checkoutInfoOutput.setColumns(20);
        checkoutInfoOutput.setLineWrap(true);
        checkoutInfoOutput.setRows(5);
        checkoutInfoOutput.setFocusable(false);
        jScrollPane1.setViewportView(checkoutInfoOutput);

        GuestInfoLabel.setText("Guest Info");

        checkoutOutputField.setEditable(false);
        checkoutOutputField.setColumns(20);
        checkoutOutputField.setLineWrap(true);
        checkoutOutputField.setRows(5);
        jScrollPane3.setViewportView(checkoutOutputField);

        cashButton.setText("Pay with Cash");
        cashButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashButtonActionPerformed(evt);
            }
        });

        totalAmountDueLabel.setText("Total Amount Due:");

        totalAmountDueField.setFocusable(false);

        changeDueField.setEditable(false);
        changeDueField.setFocusable(false);

        changeDueLabel.setText("Change Due:");

        amountPaidLabel.setText("Amount Paid:");

        javax.swing.GroupLayout checkoutTabLayout = new javax.swing.GroupLayout(checkoutTab);
        checkoutTab.setLayout(checkoutTabLayout);
        checkoutTabLayout.setHorizontalGroup(
            checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkoutTabLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10)
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkoutTabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(checkoutTabLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(CheckOutButton))))
                    .addGroup(checkoutTabLayout.createSequentialGroup()
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkoutTabLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guestIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckoutGuestSearchButton))
                            .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(checkoutTabLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ccMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ccYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(paymentInfoLabel)
                                .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(checkoutTabLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ccCVVField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, checkoutTabLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ccNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(checkoutTabLayout.createSequentialGroup()
                                    .addComponent(totalAmountDueLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalAmountDueField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(checkoutTabLayout.createSequentialGroup()
                                    .addGap(67, 67, 67)
                                    .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(checkoutTabLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(cashButton))
                                        .addComponent(ProcessPaymentButton))))
                            .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, checkoutTabLayout.createSequentialGroup()
                                    .addComponent(amountPaidLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(amountPaidField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, checkoutTabLayout.createSequentialGroup()
                                    .addComponent(changeDueLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(changeDueField))))
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(checkoutTabLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(GuestInfoLabel))
                            .addGroup(checkoutTabLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        checkoutTabLayout.setVerticalGroup(
            checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(checkoutTabLayout.createSequentialGroup()
                        .addComponent(GuestInfoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(checkoutTabLayout.createSequentialGroup()
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(guestIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckoutGuestSearchButton))
                        .addGap(36, 36, 36)
                        .addComponent(paymentInfoLabel)
                        .addGap(18, 18, 18)
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ccNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ccMonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(ccYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ccCVVField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalAmountDueLabel)
                            .addComponent(totalAmountDueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProcessPaymentButton)
                        .addGap(3, 3, 3)
                        .addComponent(cashButton)
                        .addGap(1, 1, 1)
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountPaidLabel)
                            .addComponent(amountPaidField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(changeDueLabel)
                            .addComponent(changeDueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(checkoutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckOutButton)
                        .addGap(144, 144, 144))))
        );

        mainFrame.addTab("Check Out", checkoutTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainFrame))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


//!!!ALL BUTTON ACTIONS GO BELOW!!!


    //RESERVATION TAB ACTIONS
    
    private void GuestSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuestSearchButtonActionPerformed
        reservation.gui.SearchGuestFrame SearchFrame = new reservation.gui.SearchGuestFrame(); //Create a new instance of the frame
        SearchFrame.setLocationRelativeTo(null); //Center the frame
        SearchFrame.getRootPane().setDefaultButton(SearchFrame.SearchButton);
        SearchFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_GuestSearchButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
       this.dispose();
       //restart the program
       mainframe.gui.LoginFrame master = new mainframe.gui.LoginFrame();
       master.setLocationRelativeTo(null);
       master.getRootPane().setDefaultButton(master.LoginButton);
       master.setVisible(true);
    }//GEN-LAST:event_LogOutButtonActionPerformed



    //FLOOR LAYOUT TAB ACTIONS

    private void FloorSelectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FloorSelectorItemStateChanged
        /*
        @Pre
        Display the floor layout for the floor selected.
        */
    }//GEN-LAST:event_FloorSelectorItemStateChanged

    private void newReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newReservationButtonActionPerformed
        reservation.gui.NewReservationFrame NewReservation = new reservation.gui.NewReservationFrame();
        NewReservation.setLocationRelativeTo(null); //Center the frame
        NewReservation.setVisible(true);
    }//GEN-LAST:event_newReservationButtonActionPerformed



    //KITCHEN TAB ACTIONS

    private void EditInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditInventoryButtonActionPerformed
        kitchen.gui.EditInventoryFrame EditInventoryFrame = new kitchen.gui.EditInventoryFrame(); //Create a new instance of the frame
        EditInventoryFrame.setLocationRelativeTo(null); //Center the frame
        EditInventoryFrame.getRootPane().setDefaultButton(EditInventoryFrame.SearchButton);
        EditInventoryFrame.performSearch();
        EditInventoryFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_EditInventoryButtonActionPerformed

    private void ViewInventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewInventoryButtonActionPerformed
        kitchen.gui.ViewInventoryFrame ViewInventoryFrame = new kitchen.gui.ViewInventoryFrame(); //Create a new instance of the frame
        ViewInventoryFrame.setLocationRelativeTo(null); //Center the frame
        ViewInventoryFrame.getRootPane().setDefaultButton(ViewInventoryFrame.SearchButton);
        ViewInventoryFrame.performSearch();
        ViewInventoryFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_ViewInventoryButtonActionPerformed

    private void ViewMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewMenuButtonActionPerformed
        kitchen.gui.ViewMenuFrame ViewMenu = new kitchen.gui.ViewMenuFrame(); //Create a new instance of the frame
        ViewMenu.setLocationRelativeTo(null);
        ViewMenu.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_ViewMenuButtonActionPerformed

    private void OrderHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderHistoryButtonActionPerformed
        kitchen.gui.OrderHistoryFrame OrderHistoryFrame = new kitchen.gui.OrderHistoryFrame(); //Create a new instance of the frame
        OrderHistoryFrame.setLocationRelativeTo(null); //Center the frame
        OrderHistoryFrame.getRootPane().setDefaultButton(OrderHistoryFrame.SearchButton); //make enter button do search
        OrderHistoryFrame.SearchButton.doClick(); //automatically display all records
        OrderHistoryFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_OrderHistoryButtonActionPerformed

    private void NewOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewOrderButtonActionPerformed
        kitchen.gui.OrderFrame OrderFrame = new kitchen.gui.OrderFrame(); //Create a new instance of the frame
        OrderFrame.setLocationRelativeTo(null); //Center the frame
        OrderFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_NewOrderButtonActionPerformed



    //CHECKOUT TAB ACTIONS

    private void CheckOutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        if (!(changeDueField.getText().equals(""))) {
            String gID = guestIDField.getText(); //SET GUEST ID HERE
            database.info.GuestInfo GuestSearch = new database.info.GuestInfo();

            GuestSearch.setGuestID(gID);
            GuestSearch.setLastName("99999999999999999");
                    //System.out.println("gID: "+gID);
            //System.out.println("TESTING VARS SET IN GUESTINFO: "+GuestSearch.getGuestID());

            engine.GuestDBManager manager = new engine.GuestDBManager();
            String nonSplit = manager.searchDB(GuestSearch); //return field corresponding to guest ID
            String[] split = nonSplit.split(Pattern.quote(";")); //split into pieces
            //System.out.println("email: "+split[5]);

            //Email receipt
            Engine.MailManager smtp = new Engine.MailManager(); //Create a new instance of the mail class
            //The arguments to the sendMail funtion should be the guest email from the DB and the guest's bill from the DB
            smtp.sendMail(split[5], "This is a test."); //Send the email. First argument is Guest email address, second argument is the message
            checkoutOutputField.setText("Checkout sucessful. E-mailed receipt."); //print success message
        } else {
            checkoutOutputField.setText("Error: Customer has not paid yet.");
        }
    }

    private void ProcessPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessPaymentButtonActionPerformed
        if ((!(ccNumberField.getText().equals(""))) && (ccNumberField.getText().length() == 16) && (ccNumberField.getText().matches("[0-9]+"))) {
            if ((!(ccCVVField.getText().equals(""))) && ((ccCVVField.getText().length() == 3) || (ccCVVField.getText().length() == 4)) && (ccCVVField.getText().matches("[0-9]+"))) {
                //Get current date
                DateFormat dateFormat = new SimpleDateFormat("MM/yyyy");
                Date date = new Date();
                String currentDate = dateFormat.format(date);
                String[] splitDate = currentDate.split("/");
                String ccMonth = ccMonthField.getSelectedItem().toString();
                String ccYear = ccYearField.getSelectedItem().toString();
                Boolean isExpired = false;

                if (splitDate[0].equals(ccMonth) && splitDate[1].equals(ccYear)) {
                    checkoutOutputField.setText("Error: Credit card is expired.");
                    isExpired = true;
                }

                if (Integer.parseInt(splitDate[1]) > Integer.parseInt(ccYearField.getSelectedItem().toString())) {
                    checkoutOutputField.setText("Error: Credit card is expired.");
                    isExpired = true;
                }

                if (splitDate[1].equals(ccYearField.getSelectedItem().toString()) && Integer.parseInt(splitDate[0]) > Integer.parseInt(ccMonthField.getSelectedItem().toString())) {
                    checkoutOutputField.setText("Error: Credit card is expired.");
                    isExpired = true;
                }

                if (isExpired == false) {
                    checkoutOutputField.setText("Success! Credit card accepted.");
                    amountPaidField.setText(totalAmountDueField.getText());
                    changeDueField.setText("0.00");
                    //set guest bill = 0 or whatever
                }
            } else {
                checkoutOutputField.setText("Error: invalid CVV number.");
            }
        } else {
            checkoutOutputField.setText("Error. invalid credit card number. Must be a 16 digit integer.");
        }
    }//GEN-LAST:event_ProcessPaymentButtonActionPerformed

    private void CheckoutGuestSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutGuestSearchButtonActionPerformed
        //here the button calls on the search frame from the reservation.gui package, same functionality needed
        reservation.gui.SearchGuestFrame SearchFrame = new reservation.gui.SearchGuestFrame(); //Create a new instance of the frame
        SearchFrame.setLocationRelativeTo(null); //Center the frame
        SearchFrame.getRootPane().setDefaultButton(SearchFrame.SearchButton);
        SearchFrame.setVisible(true); //Make the frame visible
    }//GEN-LAST:event_CheckoutGuestSearchButtonActionPerformed

    private void guestIDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_guestIDFieldFocusLost
        
        if (!(guestIDField.getText().equals(""))) { //TODO: Should actually validate that it's a real guest ID
            try {
                database.info.GuestInfo GuestSearch = new database.info.GuestInfo();
                GuestSearch.setGuestID(guestIDField.getText());
                GuestSearch.setLastName("99999999999999999999"); //a value that should never be in DB
      
                engine.GuestDBManager manager = new engine.GuestDBManager();
                String nonSplit = manager.searchDB(GuestSearch); //return field corresponding to guest ID
                String[] split = nonSplit.split(Pattern.quote(";")); //split into pieces
                checkoutInfoOutput.setText("Guest ID: " + split[0] + "\nFirst Name: " + split[1] + "\nLast Name: " + split[2] + "\nAddress: " + split[3] + "\nPhone Number: " + split[4] + "\nEmail Address: " + split[5]);
                
                try {
                    totalAmountDueField.setText(split[6]);
                } catch (Exception e){
                    totalAmountDueField.setText("149.99");
                }
                //ALSO PRINT BILLING INFORMATION TO checkoutBillOutput
                //totalAmountDueField.setText(split[6]);
            } catch (IndexOutOfBoundsException e) {
                 checkoutInfoOutput.setText("Error: there are no guests in the database with the ID: "+guestIDField.getText());
            }
        }
    }//GEN-LAST:event_guestIDFieldFocusLost

    private void cashButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashButtonActionPerformed
        if(amountPaidField.getText().equals("")){
            checkoutOutputField.setText("Error: Please enter the amount paid in cash by the guest.");
        } else {
            try {
                changeDueField.setText(new DecimalFormat("#.##").format(Double.parseDouble(amountPaidField.getText()) - Double.parseDouble(totalAmountDueField.getText())));
                checkoutOutputField.setText("Cash payment authorized: Please\n put cash in the register.");
            } catch (NumberFormatException e) {
                checkoutOutputField.setText("Error: Total amount due field is blank.");
            }
        }
    }//GEN-LAST:event_cashButtonActionPerformed

    private void mainFrameStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainFrameStateChanged
        JTabbedPane TabFrame = (JTabbedPane) evt.getSource();
        int index = TabFrame.getSelectedIndex();
        if (index == 2){
            orderSearch();
        }
    }//GEN-LAST:event_mainFrameStateChanged

    private void CurrentOrderTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CurrentOrderTableFocusGained
        try {
            String query = CurrentOrderTable.getValueAt(CurrentOrderTable.getSelectedRow(), 0).toString();

            database.info.OrderInfo OrderSearch = new database.info.OrderInfo();

            OrderSearch.setOrderID(query);
            boolean rfp = false;
            engine.OrderDBManager orderManager = new engine.OrderDBManager();
            String nonSplit = orderManager.searchDB(OrderSearch); //return fields
            String[] split = nonSplit.split(";");
            String[] orderList = split[5].split(",");
            String formattedOutput1 = "Order ID: " + split[0] + "\nGuest ID: " + split[1] + "\nGuest Name: " + split[2] + " " + split[3] + "\nRoom Number: " + split[4] + "\nSpecial Requests: " + split[6] + "\n\n";
            String formattedOutput2 = "------------\n#   Item\n------------\n";
            for (int i = 0; i < orderList.length; i++) {
                String[] subSplit = orderList[i].split(":");
                formattedOutput2 += (subSplit[1] + "    " + subSplit[0] + "\n");
            }
            if (split[8].equals("0")) {
                rfp = false;
            } else {
                rfp = true;
            }
            String formattedOutput3 = "\nTotal Cost: " + split[7] + "\n\nReady For Pickup: " + rfp;
            ActiveOrderOutput.setText(formattedOutput1 + formattedOutput2 + formattedOutput3);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_CurrentOrderTableFocusGained

    private void CurrentOrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurrentOrderTableMouseClicked
        String query = CurrentOrderTable.getValueAt(CurrentOrderTable.getSelectedRow(), 0).toString();

        database.info.OrderInfo OrderSearch = new database.info.OrderInfo();
        
        OrderSearch.setOrderID(query);
        boolean rfp = false;

        engine.OrderDBManager orderManager = new engine.OrderDBManager();
        String nonSplit = orderManager.searchDB(OrderSearch); //return fields
        String[] split = nonSplit.split(";");
        String[] orderList = split[5].split(",");
        String formattedOutput1 = "Order ID: "+split[0]+"\nGuest ID: "+split[1]+"\nGuest Name: "+split[2]+" "+split[3]+"\nRoom Number: "+split[4]+"\nSpecial Requests: "+split[6]+"\n\n";
        String formattedOutput2 = "------------\n#   Item\n------------\n";
        for (int i = 0; i < orderList.length; i++){
            String[] subSplit = orderList[i].split(":");
            formattedOutput2 += (subSplit[1]+"    "+subSplit[0]+"\n");
        }
        if(split[8].equals("0")){
            rfp = false;
        } else {
            rfp = true;
        }
        String formattedOutput3 = "\nTotal Cost: "+split[7]+"\n\nReady For Pickup: "+rfp;
        ActiveOrderOutput.setText(formattedOutput1+formattedOutput2+formattedOutput3);
    }//GEN-LAST:event_CurrentOrderTableMouseClicked

    private void CurrentOrderTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CurrentOrderTableKeyReleased
        String query = CurrentOrderTable.getValueAt(CurrentOrderTable.getSelectedRow(), 0).toString();

        database.info.OrderInfo OrderSearch = new database.info.OrderInfo();
        
        OrderSearch.setOrderID(query);
        boolean rfp = false;

        engine.OrderDBManager orderManager = new engine.OrderDBManager();
        String nonSplit = orderManager.searchDB(OrderSearch); //return fields
        String[] split = nonSplit.split(";");
        String[] orderList = split[5].split(",");
        String formattedOutput1 = "Order ID: "+split[0]+"\nGuest ID: "+split[1]+"\nGuest Name: "+split[2]+" "+split[3]+"\nRoom Number: "+split[4]+"\nSpecial Requests: "+split[6]+"\n\n";
        String formattedOutput2 = "------------\n#   Item\n------------\n";
        for (int i = 0; i < orderList.length; i++){
            String[] subSplit = orderList[i].split(":");
            formattedOutput2 += (subSplit[1]+"    "+subSplit[0]+"\n");
        }
        if(split[8].equals("0")){
            rfp = false;
        } else {
            rfp = true;
        }
        String formattedOutput3 = "\nTotal Cost: "+split[7]+"\n\nReady For Pickup: "+rfp;
        ActiveOrderOutput.setText(formattedOutput1+formattedOutput2+formattedOutput3);
    }//GEN-LAST:event_CurrentOrderTableKeyReleased

    private void CurrentReservationTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CurrentReservationTableFocusGained
        reservationSearch(); //update reservation table
    }//GEN-LAST:event_CurrentReservationTableFocusGained

    private void CurrentReservationTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurrentReservationTableMouseClicked
        reservationSearch(); //update reservation table
    }//GEN-LAST:event_CurrentReservationTableMouseClicked

    private void CurrentReservationTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CurrentReservationTableKeyReleased
        reservationSearch(); //update reservation table
    }//GEN-LAST:event_CurrentReservationTableKeyReleased



    //SEARCH/UPDATE TAB ACTIONS

    //N/A so far
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainContainerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainContainerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainContainerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainContainerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainContainerFrame().setVisible(true);
            }
        });
    }
    
    public static void orderSearch() {
        //display all items
        String query = "";
        database.info.OrderInfo OrderSearch = new database.info.OrderInfo();

        try {
            OrderSearch.setFirstName(query);
        } catch (NullPointerException e) {
            //stuff
        }
        engine.OrderDBManager manager = new engine.OrderDBManager();
        try {
            ArrayList<String> output = manager.printAllRecords(OrderSearch);

            String listString = "";
            for (String s : output) {
                listString += s + "\t";
            }
            String[] split = listString.split(Pattern.quote("\t")); //split into pieces

            DefaultTableModel model = (DefaultTableModel) CurrentOrderTable.getModel();
            model.setRowCount(0);
            for (int i = 2; i < split.length; i++) {
                if (i % 2 == 0) {
                    String[] subsplit = split[i].split(Pattern.quote(";"));
                    String[] timeSplit = subsplit[9].split(" ");
                    String[] newArr = {subsplit[0], timeSplit[0],timeSplit[1],subsplit[2] + " " + subsplit[3]};
                    model.addRow(newArr);
                }
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            //stuff
        }
    }
    
    public static void reservationSearch() {
        //display all items
        String query = "";
        database.info.ReservationInfo ReservationSearch = new database.info.ReservationInfo();
        database.info.GuestInfo GuestSearch = new database.info.GuestInfo();

        try {
            ReservationSearch.setGuestID(query);
        } catch (NullPointerException e) {
            //if no records exist, display nothing
        }
        engine.ReservationDBManager reservationManager = new engine.ReservationDBManager();
        engine.GuestDBManager guestManager = new engine.GuestDBManager();
        try {
            
            ArrayList<String> reservationOutput = reservationManager.printAllRecords(ReservationSearch);
            ArrayList<String> guestOutput = guestManager.printAllRecords(GuestSearch);
            
             String ReservationString = "";
             for (String s : reservationOutput) {
                ReservationString += s + "\t"; //make all records into 1 string
             }
            
            String GuestString = "";
            for (String s : guestOutput) {
                GuestString += s + "\t"; //make all records into 1 string
            }
            
            String[] ReservationSplit = ReservationString.split(Pattern.quote("\t")); //split into pieces
            String[] GuestSplit = GuestString.split(Pattern.quote("\t")); //split into pieces

            DefaultTableModel model = (DefaultTableModel) CurrentReservationTable.getModel();
            model.setRowCount(0);
            for (int i = 0; i <= 8; i++) {
                String[] GuestSubSplit = {};
               if (i <= 6){
                    GuestSubSplit = GuestSplit[i].split(Pattern.quote(";"));
               }
               String[] ReservationSubSplit = ReservationSplit[i].split(Pattern.quote(";"));
            
               //How to use newArr: first field should be GuestID, second field should be First Name + " " + Last Name
               // third field should be number of persons,
               //fourth field should be RoomNumber, fifth field should be Check In Date, sixth field should  be Check Out Date
               DateFormat dateFormat = new SimpleDateFormat("MM/dd/yy");
               String[] checkIn = ReservationSubSplit[4].split(" ");
               String[] checkOut = ReservationSubSplit[3].split(" ");
               String[] newArr = {GuestSubSplit[0],ReservationSubSplit[1],GuestSubSplit[1] + " " + GuestSubSplit[2],ReservationSubSplit[5],checkIn[0]+"/"+checkIn[1]+"/"+checkIn[2],checkOut[0]+"/"+checkOut[1]+"/"+checkOut[2]};
               model.addRow(newArr);
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            //error, probably with searches
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ActiveOrderOutput;
    private javax.swing.JButton CheckOutButton;
    private javax.swing.JButton CheckoutGuestSearchButton;
    private static javax.swing.JTable CurrentOrderTable;
    private javax.swing.JLabel CurrentOrdersLabel1;
    private static javax.swing.JTable CurrentReservationTable;
    private javax.swing.JButton EditInventoryButton;
    private javax.swing.JLabel GuestInfoLabel;
    private javax.swing.JButton GuestSearchButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton NewOrderButton;
    private javax.swing.JButton OrderHistoryButton;
    private javax.swing.JButton ProcessPaymentButton;
    private javax.swing.JButton ViewInventoryButton;
    private javax.swing.JButton ViewMenuButton;
    private javax.swing.JLabel activeOrdersLabel;
    private javax.swing.JTextField amountPaidField;
    private javax.swing.JLabel amountPaidLabel;
    private javax.swing.JButton cashButton;
    private javax.swing.JTextField ccCVVField;
    private javax.swing.JComboBox ccMonthField;
    private javax.swing.JTextField ccNumberField;
    private javax.swing.JComboBox ccYearField;
    private javax.swing.JTextField changeDueField;
    private javax.swing.JLabel changeDueLabel;
    private javax.swing.JTextArea checkoutInfoOutput;
    private javax.swing.JTextArea checkoutOutputField;
    private javax.swing.JPanel checkoutTab;
    private javax.swing.JPanel floorLayoutTab;
    private javax.swing.JTextField guestIDField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel kitchenPanel;
    private javax.swing.JPanel kitchenTab;
    private javax.swing.JTabbedPane mainFrame;
    private javax.swing.JButton newReservationButton;
    private javax.swing.JLabel paymentInfoLabel;
    private javax.swing.JPanel reserveTab;
    private javax.swing.JTextField totalAmountDueField;
    private javax.swing.JLabel totalAmountDueLabel;
    // End of variables declaration//GEN-END:variables
}
